<center> Mini Course -  Linear Algebra
<center> Hands-on Tutorial Day - 4
<center> Data Visualisation

<h1> Contents: </h1>
1. Scalar  <br />
2. Vector <br />
3. Matrix <br />
4. Tensor <br />


###The study of linear algebra involves several types of mathematical objects:

####Scalars: A scalar is just a single number, all numbers we know from algebra are referred to as scalars in linear algebra. For instance, the number [12] is a scalar

In [ ]:
# Declare a scalar as an int
s = 3
s

3

In [ ]:
# Declare s scalar as an array
import numpy as np
s_array = np.array(3)
print(s_array)

3


####Vectors: A vector is an array of numbers. Vectors are used in science to describe anything that has both magnitude and a direction

In [ ]:
# Create a vector
v = np.array([3,-5,6,1])
print(v)
len(v)

[ 3 -5  6  1]


4

In [ ]:
magnitude = np.linalg.norm(v)
magnitude

8.426149773176359

In [ ]:
import math

In [ ]:
#magnitude = math.sqrt(sum(i**2 for i in v))
magnitude = (sum(i**2 for i in v))**(0.5)
magnitude

8.426149773176359

In [ ]:
import numpy as np
import math

The cosine of the angle between two nonzero vectors is equal to the dot product of the vectors divided by the product of their lengths

In [ ]:
a = np.array([2,-3,4,7])
b = np.array([5,3,2,-1])
cosine_angle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
print(np.linalg.norm(a))
print(np.arccos(cosine_angle)*180/math.pi)

8.831760866327848
87.92189136697016


We can use scalars in vectorized operations

In [ ]:
v = np.array([3,-5,6,1])
v*3
v+3
a = np.array([1,2,3,0])
b = np.array([4,5,6,7])
a+b
a-b

array([-3, -3, -3, -7])

####Matrix: A matrix is a collection of numbers ordered in rows and columns

In [ ]:
# Create a matrix
m = np.array([[2,3,1], [5,6,3]])
print(m)
m.shape

[[2 3 1]
 [5 6 3]]


(2, 3)

In [ ]:
M = np.arange(10).reshape(2,5)
print(M)
# Size of a matrix
# Specific value
print(M[1,3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
8


In [ ]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Determinant of a matrix: The determinant of a matrix is the scalar value or number calculated using a square matrix

In [ ]:
m = np.array([[2,3], [4,5]])
m
np.linalg.det(m)

-2.0

Transpose of a matrix:
The transpose of a matrix is found by interchanging its rows into columns or columns into rows

In [ ]:
c = np.array([[1,2,3,4], [8,4,2,0], [4,0,3,2]])
print(c)
print(c.T)

[[1 2 3 4]
 [8 4 2 0]
 [4 0 3 2]]
[[1 8 4]
 [2 4 0]
 [3 2 3]
 [4 0 2]]


Inverse of a matrix: The inverse of a square matrix A, sometimes called a reciprocal matrix, is a matrix $A^{(-1)}$ such that $A.A^{(-1)} = A^{(-1)}.A = I$,	where I is the identity matrix (applicable for invertible, non-singular, square matrix)



In [ ]:
e = np.array([[2,4], [3,5]])
inverse_matrix = np.linalg.inv(e)
print(e)
print(inverse_matrix)
print(e.dot(inverse_matrix))
print(inverse_matrix.dot(e))

[[2 4]
 [3 5]]
[[-2.5  2. ]
 [ 1.5 -1. ]]
[[1.00000000e+00 4.44089210e-16]
 [2.22044605e-16 1.00000000e+00]]
[[1.00000000e+00 1.99840144e-15]
 [0.00000000e+00 1.00000000e+00]]


Multiplication of the matrices

In [ ]:
# Matrix multiplication can be done in 3 ways
M = np.array([[1,6,6],[8,9,3],[2,3,7]])
N = np.array([[1,6,6],[8,9,3],[2,3,7]])
print(np.dot(M,N))
print(M@N)
print(np.matmul(M,N))

[[ 61  78  66]
 [ 86 138  96]
 [ 40  60  70]]
[[ 61  78  66]
 [ 86 138  96]
 [ 40  60  70]]
[[ 61  78  66]
 [ 86 138  96]
 [ 40  60  70]]


In [ ]:
# Matrix power
M = np.array([[1,2],[2,3]])
print(M)
print(np.linalg.matrix_power(M, 3))
print(M@M)

[[1 2]
 [2 3]]
[[21 34]
 [34 55]]
[[ 5  8]
 [ 8 13]]


Rank of a matrix: In linear algebra, the rank of a matrix A is the dimension of the vector space generated by its columns. This corresponds to the maximal number of linearly independent columns of A

In [ ]:
# Rank of a martix
#M = np.array([[1,6,6],[8,9,3],[2,3,7]])
M = np.array([[1,2,3],[2,4,6],[2,3,7]])
M
np.linalg.matrix_rank(M)

2

Let A be an n × n matrix. <br /> An eigenvector of A is a nonzero vector v in R n such that Av = λ v , for some scalar λ <br /> An eigenvalue of A is a scalar λ such that the equation Av = λ v has a nontrivial solution <br /> If Av = λ v for v A = 0, we say that λ is the eigenvalue for v , and that v is an eigenvector for λ <br />The German prefix “eigen” roughly translates to “self” or “own”

In [ ]:
A = np.matrix([[2,3,5,2], [4,6,10,4], [4,3,0,1], [2,3,1,6]])
print(A)
print(np.linalg.matrix_rank(A))
eig_val, eig_vect = np.linalg.eig(A)
print(eig_val)
print(eig_vect)

[[ 2  3  5  2]
 [ 4  6 10  4]
 [ 4  3  0  1]
 [ 2  3  1  6]]
3
[ 1.41001040e+01 -4.24421795e+00 -3.73171034e-16  4.14411392e+00]
[[-0.38363531 -0.31218047  0.5497625  -0.17923096]
 [-0.76727061 -0.62436094 -0.79410139 -0.35846192]
 [-0.30159213  0.69406569  0.18325417 -0.21775101]
 [-0.41612732  0.17603863  0.18325417  0.88992461]]


Reconstruction of a matrix from its eigen value and eigen vector $A=PΛP{^(−1)}$ , where  P  is the matrix whose columns are the eigenvectors of  A  and  Λ  is a diagonal matrix whose diagonal entries are the eigenvalues of  A  (listed in the same order as their corresponding eigenvectors listed in  P )

In [ ]:
eig_val

array([ 1.41001040e+01, -4.24421795e+00, -3.73171034e-16,  4.14411392e+00])

In [ ]:
eig_vect

matrix([[-0.38363531, -0.31218047,  0.5497625 , -0.17923096],
        [-0.76727061, -0.62436094, -0.79410139, -0.35846192],
        [-0.30159213,  0.69406569,  0.18325417, -0.21775101],
        [-0.41612732,  0.17603863,  0.18325417,  0.88992461]])

In [ ]:
#Reconstruction of a matrix from its eigen value and eigen vector
Z = eig_vect.dot(np.diag(eig_val)).dot(np.linalg.inv(eig_vect))
print(A)
print(Z)

[[ 2  3  5  2]
 [ 4  6 10  4]
 [ 4  3  0  1]
 [ 2  3  1  6]]
[[ 2.00000000e+00  3.00000000e+00  5.00000000e+00  2.00000000e+00]
 [ 4.00000000e+00  6.00000000e+00  1.00000000e+01  4.00000000e+00]
 [ 4.00000000e+00  3.00000000e+00 -1.39137055e-15  1.00000000e+00]
 [ 2.00000000e+00  3.00000000e+00  1.00000000e+00  6.00000000e+00]]


In [ ]:
np.diag(eig_val)

array([[ 1.41001040e+01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -4.24421795e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.73171034e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.14411392e+00]])

In [ ]:
#Matrix power using eiven value and eigen vector
A3 = eig_vect.dot(np.linalg.matrix_power(np.diag(eig_val), 2)).dot(np.linalg.inv(eig_vect))
print(A3)
print(A@A)

[[40. 45. 42. 33.]
 [80. 90. 84. 66.]
 [22. 33. 51. 26.]
 [32. 45. 46. 53.]]
[[40 45 42 33]
 [80 90 84 66]
 [22 33 51 26]
 [32 45 46 53]]


Solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2:

In [ ]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
x

array([-1.,  1.])

Singular Value Decomposition

The Singular Value Decomposition (SVD) of a matrix is a factorization of that matrix into three matrices. It has some interesting algebraic properties and conveys important geometrical and theoretical insights about linear transformations. It also has some important applications in data science

In [ ]:
A = np.matrix([[-2,1,4,5], [2,0,4,-2], [3,0,9,-1]])
U, E, V = np.linalg.svd(A)
print(U)
print(E)
print(V)

[[ 0.30215165  0.92737206 -0.22064778]
 [ 0.40173501 -0.3337862  -0.85275774]
 [ 0.86447288 -0.16902022  0.47341188]]
[10.96291785  6.38151364  0.30119075]
[[ 0.25473012  0.02756124  0.966513   -0.01433785]
 [-0.47471139  0.14532164  0.13369264  0.85770449]
 [ 0.51799636 -0.73258485 -0.10928344  0.42785085]
 [ 0.6644106   0.6644106  -0.1898316   0.2847474 ]]


Characteristics of SVD

U:  mxn matrix of the orthonormal eigenvectors of $AA^{T}$        
$V^{T}$: transpose of a nxn matrix containing the orthonormal eigenvectors of $A^{T}A$  
W:  a nxn diagonal matrix of the singular values which are the square roots of the eigenvalues of $A^{T}A$          .

In [ ]:
x1 = U.dot(U.T)
x2 = V.dot (V.T)
print(x1)
print(x2)

[[ 1.00000000e+00 -1.80838017e-16 -7.52434030e-17]
 [-1.80838017e-16  1.00000000e+00  2.72860953e-16]
 [-7.52434030e-17  2.72860953e-16  1.00000000e+00]]
[[ 1.00000000e+00  1.00925500e-16 -3.98965716e-17 -1.16899019e-16]
 [ 1.00925500e-16  1.00000000e+00 -1.96803287e-16 -4.47444641e-17]
 [-3.98965716e-17 -1.96803287e-16  1.00000000e+00  2.09447310e-16]
 [-1.16899019e-16 -4.47444641e-17  2.09447310e-16  1.00000000e+00]]


Null space (Kernel) and nullity

In [ ]:
from sympy import Matrix
import numpy as np

A = np.matrix([[1, 2, 3], [2, 4, 6], [3, 10, 9]])
A = Matrix(A)

# Null Space of A
NullSpace = A.nullspace()   # Here NullSpace is a list

NullSpace = Matrix(NullSpace)   # Here NullSpace is a Matrix
#print("Null Space : ", NullSpace)

# checking whether NullSpace satisfies the
# given condition or not as A * NullSpace = 0
# if NullSpace is null space of A
print(Matrix(A * NullSpace))
#NullSpace

Matrix([[0], [0], [0]])


Nullity of A + Rank of A = Total number of attributes of A (i.e. total number of columns in A)

In [ ]:
# Number of Columns
NoC = A.shape[1]

# Rank of A
rank = A.rank()
print(rank)

# Nullity of the Matrix
nullity = NoC - rank
nullity

2


1

Find the nullspace, nullity and rank of the matrix

A = np.matrix([[2,3,5,2], [4,6,10,4], [4,3,0,1], [2,3,1,6]])


In [ ]:
A = np.matrix([[2,3,5,2], [4,6,10,4], [4,6,2,12], [2,3,1,6]])
A = Matrix(A)
nullspace = A.nullspace()
Matrix(nullspace)

#A.shape[1]

#A.rank()

Matrix([
[-3/2],
[   1],
[   0],
[   0],
[-7/2],
[   0],
[   1],
[   1]])

####Tensor: In mathematics, a tensor is an algebraic object that describes a multilinear relationship between sets of algebraic objects related to a vector space

In [ ]:
#Create a tensor
m1 = np.array([[2,3,1], [5,6,3]])
m2 = np.array([[3,-1,5], [9,2,4]])

#Tensor: m1+m2
t = np.array([m1,m2])
print(t)
print(t.shape)

[[[ 2  3  1]
  [ 5  6  3]]

 [[ 3 -1  5]
  [ 9  2  4]]]
(2, 2, 3)


In [ ]:
T = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]]])
print(T)
print(T.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)


Tensor Operations

In [ ]:
import numpy as np
A = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

B = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

C = A+B
C = A-B
C = A*B
C = A/B
C

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Tensor dot product

In [ ]:
from numpy import tensordot

A = np.array([1, 2])
B = np.array([3, 4])

C = tensordot(A, B, axes=0)
C

array([[3, 4],
       [6, 8]])

In [ ]:
import scipy

#### Optimization

1. Function : $y = x_{1} +  x_{2}$

2. Constraints: $x_1\ \ge\ 4$  
$\hspace{25mm}x_2\ \le\ 6$  
$\hspace{25mm}x_1\ + x_2\ \le\ 8$

![LP.png](https://drive.google.com/uc?export=view&id=1NkAjhlf--B9HGYRDFYZ09-jkv96RVTNe)

To maximize our function, the objective f(x) = $(c^T.x)$ is defined by $min -f(x)$ and the inequality equations needs to be changed to match the inequality constraint format

In [ ]:
obj = [-1,-1]
lhs_ineq = [[-1,0],[0,1],[1,1]]
rhs_ineq = [-4,6,8]
opt = scipy.optimize.linprog(c=obj,A_ub=lhs_ineq,b_ub = rhs_ineq)
opt

The *linprog()* output reports the minimized/maximized objective function value (opt.fun) and the solution vector (opt.x)

##### Question



$maximize\ z = x + 2y$  
$subject\ to \ 2x + y\ \le\ 20$  
$\hspace{20mm} -4x+5y\ \le\ 10$  
$\hspace{20mm}  x - 2y\ \le\ 2$  
$\hspace{20mm}  -x + 5y\ =\ 15$  
$\hspace{20mm}  x\ \ge\ 0,\ y\ \ge\ 0$  


###### Solution

In [ ]:
obj = [-1,-2]
lhs_ineq = [[ 2,  1], [-4,  5], [ 1, -2]]
rhs_ineq = [20,10,2]
lhs_eq = [[-1, 5]]
rhs_eq = [15]

In [ ]:
# Bounds
import math
bound = [[0,math.inf],[0,math.inf]]

In [ ]:
from scipy.optimize import linprog
# Optimization
opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq,
              A_eq=lhs_eq, b_eq=rhs_eq, bounds=bound)
opt